# Generated by Django 4.2.4 on 2023-09-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_enrolleduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolleduser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
