# Generated by Django 4.2.4 on 2023-09-19 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_discussion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
