# Generated by Django 4.2.4 on 2023-11-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='attempt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
