# Generated by Django 4.2.4 on 2023-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_grade_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
