# Generated by Django 4.2.4 on 2023-11-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_quiz_is_visible_quiz_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
