# Generated by Django 4.2.4 on 2023-11-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0022_remove_studentquestion_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='term',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
