# Generated by Django 4.2.4 on 2023-11-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0024_finalgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgrade',
            name='term',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
