# Generated by Django 4.2.4 on 2024-02-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_module_modulequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulequestion',
            old_name='quiz',
            new_name='module',
        ),
    ]
