# Generated by Django 5.0.2 on 2024-02-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0027_rename_quiz_modulequestion_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulequestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
