# Generated by Django 5.0.2 on 2024-02-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0028_modulequestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulequestion',
            name='option1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulequestion',
            name='option2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulequestion',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulequestion',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
