# Generated by Django 5.0.2 on 2024-03-01 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0029_alter_modulequestion_option1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulequestion',
            name='image',
        ),
        migrations.AddField(
            model_name='modulequestion',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ModuleSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.module')),
            ],
        ),
    ]
