# Generated by Django 5.0.2 on 2024-03-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0030_remove_modulequestion_image_modulequestion_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefab', models.ImageField(blank=True, null=True, upload_to='prefabs/')),
            ],
        ),
    ]
