# Generated by Django 5.0.2 on 2024-03-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0033_rename_defualtmodule_modulesection_defaultmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulequestion',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
