# Generated by Django 5.0.2 on 2024-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0034_alter_modulequestion_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulequestion',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True),
        ),
    ]
