# Generated by Django 5.0.2 on 2024-04-15 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0035_alter_modulequestion_correct_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_values', models.JSONField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
