# Generated by Django 5.0.2 on 2024-04-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0036_studentmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='input_values',
            field=models.JSONField(null=True),
        ),
    ]
