# Generated by Django 4.2.11 on 2024-04-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0038_studentmodule_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=500)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.module')),
            ],
        ),
    ]
