# Generated by Django 4.2.11 on 2024-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0039_shortanswerquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortanswerquestion',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
