# Generated by Django 4.2.11 on 2024-04-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0040_shortanswerquestion_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortAnswerQuestion',
            new_name='ShortAnswer',
        ),
    ]
