# Generated by Django 5.0.2 on 2024-04-17 22:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0041_rename_shortanswerquestion_shortanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulequestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
