# Generated by Django 5.0.2 on 2024-04-19 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0042_alter_modulequestion_id_alter_shortanswer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.module'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.module'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='module_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.modulequestion'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.quiz'),
        ),
        migrations.AlterField(
            model_name='studentquestion',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.quiz'),
        ),
    ]
