# Generated by Django 5.0.2 on 2024-04-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0043_grade_module_studentquestion_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentShortAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=800)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
