# Generated by Django 5.0.2 on 2024-04-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0045_studentshortanswer_module_studentshortanswer_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentshortanswer',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
