# Generated by Django 4.2.11 on 2024-04-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0046_alter_studentshortanswer_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentshortanswer',
            name='attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentshortanswer',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
