# Generated by Django 4.2.11 on 2024-04-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0047_module_attempts_module_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
