# Generated by Django 5.0.2 on 2024-04-25 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0048_grade_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulesection',
            name='image',
        ),
        migrations.CreateModel(
            name='ModuleImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.modulesection')),
            ],
        ),
    ]
